src/Imie/SkillsBundle/Entity/Image.php
<?php

namespace Imie\SkillsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Imie\SkillsBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 * 
 */
class Image {

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="imageAlt", type="string", length=255)
     */
    private $imageAlt;

    /**
     * @var string
     *
     * @ORM\Column(name="imageName", type="string", length=255)
     */
    private $imageName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $path;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;
    
    private $filenameForRemove;
    
    private $temp;

    public function getAbsolutePath() {
        return null === $this->path ? null : $this->getUploadRootDir().'/'.$this->id.'.'.$this->path;
    }

    public function getWebPath() {
        return null === $this->path ? null : $this->getUploadDir() . '/' .$this->id.'.'. $this->path;
    }

    protected function getUploadRootDir() {
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir() {
        return 'uploads/img';
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->path)) {
            // store the old name to delete after the update
            $this->temp = $this->path;
            $this->path = null;
        } else {
            $this->path = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile() {
        return $this->file;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
       if (null !== $this->file) {
            $this->path = $this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
       if (null === $this->file) {
            return;
        }

        $this->file->move($this->getUploadRootDir(), $this->id.'.'.$this->file->guessExtension());

        unset($this->file);
    }

    /**
     * @ORM\PreRemove()
     */
    public function storeFilenameForRemove() {
        $this->filenameForRemove = $this->getAbsolutePath();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        if ($this->filenameForRemove) {
            unlink($this->filenameForRemove);
        }
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set imageAlt
     *
     * @param string $imageAlt
     * @return Image
     */
    public function setImageAlt($imageAlt) {
        $this->imageAlt = $imageAlt;
        $this->setImageName();

        return $this;
    }

    /**
     * Get imageAlt
     *
     * @return string 
     */
    public function getImageAlt() {
        return $this->imageAlt;
    }

    /**
     * Set imageName
     *
     * @param string $imageName
     * @return Image
     */
    public function setImageName() {
        $this->imageName = $this->imageAlt;

        return $this;
    }

    /**
     * Get imageName
     *
     * @return string 
     */
    public function getImageName() {
        return $this->imageName;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Image
     */
    public function setPath($path) {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath() {
        return $this->path;
    }

}

src/Imie/SkillsBundle/Form/UserType.php
<?php

namespace Imie\SkillsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class UserType extends AbstractType {


    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('userFirstName', null, array(
                    'label' => 'Prénom :'
                ))
                ->add('userLastName', null, array(
                    'label' => 'Nom :'
                ))
                ->add('userBirthday', 'date', array(
                    'format' => "ddMMyyyy",
                    'widget'=> 'text',
                    'label' => 'Date de naissance (dd/mm/yyyy) :'
                ))
                ->add('userPhoneNumber', 'text', array(
                    'label' => 'Numéro de téléphone :'
                ))
                ->add('userAddress', null, array(
                    'label' => 'Adresse postale :'
                ))
                ->add('email', 'email', array('label' => 'Email :', 'translation_domain' => 'FOSUserBundle'))
                ->add('username', null, array('label' => 'Pseudo :', 'translation_domain' => 'FOSUserBundle'))
                ->add('plainPassword', 'repeated', array(
                    'type' => 'password',
                    'options' => array('translation_domain' => 'FOSUserBundle'),
                    'first_options' => array('label' => 'Mot de passe :'),
                    'second_options' => array('label' => 'Confirmer mot de passe :'),
                    'invalid_message' => 'fos_user.password.mismatch',
                ))
                ->add('userDescription', null, array(
                    'label' => 'Description :'
                ))
                ->add('promo', 'entity', array(
                    'class' => 'ImieSkillsBundle:Promo',
                    'choice_label' => 'promoFullName'
                ))
                ->add('isAdmin', 'checkbox', array(
                    'label' => 'Rendre Administrateur',
                    'required' => false,
                ))
                ->add('image', new ImageType(), array(
                    'required' => false,
                    'label' => 'Image :'
                ))
                ->add('Valider', 'submit', array(
                    'attr' => array('class' => 'btn btn-primary'),
                ))
        ;
    }


    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver) {
        $resolver->setDefaults(array(
            'data_class' => 'Imie\SkillsBundle\Entity\User'
        ));
    }

    /**
     * @return string
     */
    public function getName() {
        return 'imie_skillsbundle_user';
    }

}

src/Imie/SkillsBundle/Controller/UserController.php
<?php

namespace Imie\SkillsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Imie\SkillsBundle\Entity\User;
use Imie\SkillsBundle\Entity\UserSkill;
use Imie\SkillsBundle\Form\UserType;
use Imie\SkillsBundle\Form\UserSkillType;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Imie\SkillsBundle\Form\UserModifyType;

class UserController extends Controller {

  public function indexAction() {
    if (false === $this->get('security.context')->isGranted('ROLE_USER')) {
      throw new AccessDeniedException();
    }
    $em = $this->getDoctrine()->getManager();
    $repo = $em->getRepository('ImieSkillsBundle:User');
    $users = $repo->getUsersOrderedById();
    return $this->render('ImieSkillsBundle:User:index.html.twig', array('users' => $users));
  }

  public function addAction(Request $req) {
    if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
      throw new AccessDeniedException();
    }
    $user = new User();
    $form = $this->createForm(new UserType(), $user, array(
      'action' => $this->generateUrl('imie_skills_user_add')
    ));

    $form->handleRequest($req);
    if ($form->isValid()) {
      try {
        $em = $this->getDoctrine()->getManager();
        $user->setUserFullName();
        $isAdmin = array($form->get('isAdmin')->getData());
        foreach ($isAdmin as $valid) {
          if ($valid === true) {
            $user->addRole("ROLE_ADMIN");
            $user->setSuperAdmin(true);
          }
        }
        if ($user->getImage()) {
          $user->getImage()->setImageAlt($user->getUserFullName());
        }
        $em->persist($user);
        $em->flush();
        $req->getSession()->getFlashBag()->add('success', 'Utilisateur ajouté');
        return $this->redirect($this->generateUrl('imie_skills_user_index'));
      } catch (\Doctrine\DBAL\DBALException $e) {
        $req->getSession()->getFlashBag()->add('danger', 'Erreur lors de l\'ajout :'
        . PHP_EOL . $e->getMessage());
      }
    }
    return $this->render('ImieSkillsBundle:User:add.html.twig', array(
      'form' => $form->createView()
    ));
  }

  public function addSkillAction(Request $req) {
    if (false === $this->get('security.context')->isGranted('ROLE_USER')) {
      throw new AccessDeniedException();
    }
    $userSkill = new UserSkill();

    $form = $this->createForm(new UserSkillType(), $userSkill, array(
      'action' => $this->generateUrl('imie_skills_user_addSkill')
    ));
    $form->handleRequest($req);
    if ($form->isValid()) {
      try {
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository('ImieSkillsBundle:User');
        $currentUser = $this->get('security.token_storage')->getToken()->getUser();
        $user = $repo->getUserById($currentUser->getId());
        $userSkill->setUser($user);
        $userSkill->setSkill($form->get('skill')->getData());
        $userSkill->setLevel($form->get('level')->getData()->getLevel());
        $currentUser->addSkill($userSkill);
        $em->persist($userSkill);
        $em->flush();
        $req->getSession()->getFlashBag()->add('success', 'Compétence assignée');
        return $this->redirect($this->generateUrl('imie_skills_user_addSkill'));
      } catch (\Doctrine\DBAL\DBALException $e) {
        $req->getSession()->getFlashBag()->add('danger', 'Erreur lors de l\'assignation :'
        . PHP_EOL . $e->getMessage());
      }
    }
    return $this->render('ImieSkillsBundle:UserSkill:addSkill.html.twig', array(
      'form' => $form->createView()
    ));
  }

  public function modifySkillAction(Request $req, $id) {
    if ($id != $this->get('security.token_storage')->getToken()->getUser()->getId()) {
      if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
        throw new AccessDeniedException();
      }
    }
    $em = $this->getDoctrine()->getManager();
    $repo = $em->getRepository('ImieSkillsBundle:UserSkill');
    $currentUser = $this->get('security.token_storage')->getToken()->getUser()->getId();
    $userSkillToModify = $repo->findOneById($id);
    $form = $this->createForm(new UserSkillType(), $userSkillToModify, array(
      'action' => $this->generateUrl('imie_skills_user_modifySkill', array(
        'id' => $id
      ))
    ));
    $form->handleRequest($req);
    if ($form->isValid()) {
      try {
        $userSkillToModify->setSkill($form->get('skill')->getData());
        $userSkillToModify->setLevel($form->get('level')->getData()->getLevel());
        $em->persist($userSkillToModify);
        $em->flush();
        $req->getSession()->getFlashBag()->add('success', 'Compétence modifiée');
        return $this->redirect($this->generateUrl('imie_skills_user_details', array(
          'id' => $currentUser
        )));
      } catch (\Doctrine\DBAL\DBALException $e) {
        $req->getSession()->getFlashBag()->add('danger', 'Erreur lors de la modification :'
        . PHP_EOL . $e->getMessage());
      }
    }
    return $this->render('ImieSkillsBundle:UserSkill:modifySkill.html.twig', array(
      'form' => $form->createView(),
      'id' => $id
    ));
  }

  public function deleteSkillAction(Request $req, $id) {
    if ($id != $this->get('security.token_storage')->getToken()->getUser()->getId()) {
      if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
        throw new AccessDeniedException();
      }
    }
    $em = $this->getDoctrine()->getManager();
    $repo = $em->getRepository('ImieSkillsBundle:UserSkill');
    $userSkill = $repo->getUserSkillById($id);
    $currentUser = $this->get('security.token_storage')->getToken()->getUser()->getId();
    try {
      $em->remove($userSkill);
      $em->flush();
      $req->getSession()->getFlashBag()->add('success', 'Compétence supprimée');
    } catch (\Doctrine\DBAL\DBALException $e) {
      $req->getSession()->getFlashBag()->add('danger', 'Erreur lors de la suppression :'
      . PHP_EOL . $e->getMessage());
    }
    return $this->redirect($this->generateUrl('imie_skills_user_details', array(
      'id' => $currentUser
    )));
  }

  public function detailsAction($id) {
    if (false === $this->get('security.context')->isGranted('ROLE_USER')) {
      throw new AccessDeniedException();
    }
    $em = $this->getDoctrine()->getManager();
    $repo = $em->getRepository('ImieSkillsBundle:User');
    $user = $repo->getUserById($id);
    return $this->render('ImieSkillsBundle:User:details.html.twig', array(
      'user' => $user
    ));
  }

  public function modifyAction(Request $req, $id) {
    if ($id != $this->get('security.token_storage')->getToken()->getUser()->getId()) {
      if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
        throw new AccessDeniedException();
      }
    }
    $em = $this->getDoctrine()->getManager();
    $repo = $em->getRepository('ImieSkillsBundle:User');
    $userToModify = $repo->findOneById($id);
    if($this->get('security.context')->isGranted('ROLE_ADMIN')){
      $type = new UserType();
    } else {
      $type = new UserModifyType();
    }
    $form = $this->createForm($type, $userToModify, array(
      'action' => $this->generateUrl('imie_skills_user_modify', array(
        'id' => $id
      ))
    ));
    $form->handleRequest($req);
    if ($form->isValid()) {
      try {
        $userToModify->setUserFullName();
        $em->persist($userToModify);
        $em->flush();
        $req->getSession()->getFlashBag()->add('success', 'Utilisateur modifié');
      } catch (\Doctrine\DBAL\DBALException $e) {
        $req->getSession()->getFlashBag()->add('danger', 'Erreur lors de la modification :'
        . PHP_EOL . $e->getMessage());
      }
    }
    return $this->render('ImieSkillsBundle:User:modify.html.twig', array(
      'form' => $form->createView()
    ));
  }

  public function deleteAction(Request $req, $id) {
    if (false === $this->get('security.context')->isGranted('ROLE_ADMIN')) {
      throw new AccessDeniedException();
    }
    $em = $this->getDoctrine()->getManager();
    $userRepo = $em->getRepository('ImieSkillsBundle:User');
    $userToDelete = $userRepo->getUserById($id);
    try {
      $em->remove($userToDelete);
      $em->flush();
      $req->getSession()->getFlashBag()->add('success', 'Utilisateur supprimé');
      return $this->redirect($this->generateUrl('imie_skills_user_index'));
    } catch (\Doctrine\DBAL\DBALException $e) {
      $req->getSession()->getFlashBag()->add('danger', 'Erreur lors de la suppression :'
      . PHP_EOL . $e->getMessage());
    }
    return $this->redirect($this->generateUrl('imie_skills_user_index'));
  }
}

src/Imie/SkillsBundle/Resources/views/User/add.html.twig
{% extends 'ImieSkillsBundle::layout.html.twig' %}

{% block article %}
<ol class="breadcrumb">
  <li><a href="{{ path('imie_skills_home') }}">Accueil</a></li>
  <li><a href="{{ path('imie_skills_user_index') }}">Liste des utilisateurs</a></li>
  <li class="active">Ajout d'un utilisateur</li>
</ol>
<h2><span class="glyphicon glyphicon-user"></span> Ajout d'un utilisateur</h2>
<hr/>
<a class="btn btn-primary" href="{{ path('imie_skills_user_index') }}"><span class="glyphicon glyphicon-menu-left"></span> Retour</a>
<hr/>
<form method="post" action="{{ path('imie_skills_user_add') }}" {{ form_enctype(form) }}>
  {{ form(form) }}
</form>
{% endblock article %}

src/Imie/SkillsBundle/Resources/views/User/details.html.twig
{% extends 'ImieSkillsBundle::layout.html.twig' %}

{% block article %}
<ol class="breadcrumb">
  <li><a href="{{ path('imie_skills_home') }}">Accueil</a></li>
  <li><a href="{{ path('imie_skills_user_index') }}">Liste des utilisateurs</a></li>
  <li class="active">Détails de l'utilisateur</li>
</ol>
<h2><span class="glyphicon glyphicon-user"></span> Profil de {{ user.userFullName }}</h2>
<hr/>
<a class="btn btn-primary" href="{{ path('imie_skills_user_index') }}"><span class="glyphicon glyphicon-menu-left"></span> Retour</a>
{% if (user.id == app.user.id or is_granted("ROLE_ADMIN")) %}
<a class="btn btn-warning" href="{{ path('imie_skills_user_modify', {id:user.id}) }}"><span class="glyphicon glyphicon-cog"></span> Modifier</a>
<a class="btn btn-info" href="{{ path('imie_skills_project_add') }}" role="button"><span class="glyphicon glyphicon-plus"></span> Ajouter un projet</a>
<a class="btn btn-info" href="{{ path('imie_skills_user_addSkill') }}" role="button"><span class="glyphicon glyphicon-plus"></span> Assigner une compétence</a>
{% endif %}
{% if is_granted("ROLE_ADMIN") %}
<button type="button" class="btn btn-danger" data-toggle="modal" data-target=".user"><span class="glyphicon glyphicon-trash"></span></button>
<div class="modal fade user" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body">Supprimer l'utilisateur {{ user.userFullName }} ?</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
        <a class="btn btn-danger" href="{{ path('imie_skills_user_delete', {id:user.id}) }}" role="button">Confirmer</a>
      </div>
    </div>
  </div>
</div>
{% endif %}
<hr/>
<div id="user-page-head">
  <div class="col-md-2">
    {% if user.image %}
    <img src="{{ asset(user.image.webPath) }}" alt="{{ asset(user.image.imageAlt) }}" width="128" height="128" class="img-circle">
    {% endif %}
  </div>
  <div class="col-md-5">
    <p><b>Adresse postale :</b> {{ user.userAddress }}</p>
    <p><b>Téléphone :</b> {{ user.userPhoneNumber }}</p>
    <p><b>Email :</b> {{ user.email }}</p>
    <p><b>Date de naissance :</b> {{ user.userBirthday|date('d/m/Y') }}</p>
    <p><b>Promo :</b> {% if user.promo is not null %}{{ user.promo.promoFullName }}{% endif %}</p>
    <p><b>Description :</b> {{ user.userDescription }}</p>
  </div>
  <div class="col-md-5">
    <h4>Compétences</h4>
    <table class="table table-striped">
      <thead>
        <th class="col-md-4">Nom</th>
        <th class="col-md-3">Niveau</th>
        <th class="col-md-3">Modifier</th>
        <th class="col-md-2">Supprimer</th>
      </thead>
      <tbody>
        {% for tabSkill in user.skills %}
        <tr>
          <td>{{ tabSkill.skill.skillName }}</td>
          <td>{{ tabSkill.level }}</td>
          {% if (user.id == app.user.id or is_granted("ROLE_ADMIN"))%}
          <td><a class="btn btn-warning" href="{{ path('imie_skills_user_modifySkill', {id:tabSkill.id}) }}" role="button"><span class="glyphicon glyphicon-cog"></span></a></td>
          <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target=".skill{{tabSkill.id}}"><span class="glyphicon glyphicon-trash"></span></button>
            <div class="modal fade skill{{tabSkill.id}}" tabindex="-1" role="dialog">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-body">Supprimer la compétence {{ tabSkill.skill.skillName }} de niveau {{ tabSkill.level }} ?</div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <a class="btn btn-danger" href="{{ path('imie_skills_user_deleteSkill', {id: tabSkill.id}) }}" role="button">Confirmer</a>
                  </div>
                </div>
              </div>
            </div>
          </td>
          {% else %}
          <td></td>
          <td></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr/>
{% if (user.createdProjects or user.managedProjects or joinedProjects) %}
<h4>Projets dont vous êtes Fondateur</h4>
<table class="table table-striped user-page-table">
  <thead>
    <th class="col-md-6">Nom</th>
    <th class="col-md-3">Chef de projet</th>
    <th class="col-md-1">Phase</th>
    <th class="col-md-1">Modifier</th>
    <th class="col-md-1">Supprimer</th>
  </thead>
  <tbody>
    {% for proj in user.createdProjects %}
    <tr>
      <td><a href="{{ path('imie_skills_project_details', {id:proj.id})}}">{{ proj.projectName }}</a></td>
      <td>{% if proj.manager is not null %}{{ proj.manager.userFullName }}{% else %}À recruter{% endif %}</td>
      <td>{{ proj.state.statut }}</td>
      <td><a class="btn btn-warning" href="{{ path('imie_skills_project_modify', {id:proj.id}) }}" role="button"><span class="glyphicon glyphicon-cog"></span></a></td>
      <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target=".project{{proj.id}}"><span class="glyphicon glyphicon-trash"></span></button>
        <div class="modal fade project{{proj.id}}" tabindex="-1" role="dialog">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-body">Supprimer {{ proj.projectName }} ?</div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                <a class="btn btn-danger" href="{{ path('imie_skills_project_delete', {id:proj.id}) }}" role="button">Confirmer</a>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<hr/>
<h4>Projets dont vous êtes Chef de projet</h4>
<table class="table table-striped user-page-table">
  <thead>
    <th class="col-md-3">Nom</th>
    <th class="col-md-6">Fondateur</th>
    <th class="col-md-3">Phase</th>
  </thead>
  <tbody>
    {% for proj in user.managedProjects %}
    <tr>
      <td><a href="{{ path('imie_skills_project_details', {id:proj.id})}}">{{ proj.projectName }}</a></td>
      <td>{{ proj.creator.userFullName }}</td>
      <td>{{ proj.state.statut }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<hr/>
<h4>Projets dont vous faites parti</h4>
<table class="table table-striped user-page-table">
  <thead>
    <th class="col-md-3">Nom</th>
    <th class="col-md-3">Fondateur</th>
    <th class="col-md-3">Chef de projet</th>
    <th class="col-md-3">Phase</th>
  </thead>
  <tbody>
    {% for proj in user.joinedProjects %}
    <tr>
      <td><a href="{{ path('imie_skills_project_details', {id:proj.id})}}">{{ proj.projectName }}</a></td>
      <td>{{ proj.creator.userFullName }}</td>
      <td>{% if proj.manager is not null %}{{ proj.manager.userFullName }}{% else %}À recruter{% endif %}</td>
      <td>{{ proj.state.statut }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% endblock article %}

src/Imie/SkillsBundle/Resources/views/User/index.html.twig
{% extends 'ImieSkillsBundle::layout.html.twig' %}

{% block article %}
<ol class="breadcrumb">
  <li><a href="{{ path('imie_skills_home') }}">Accueil</a></li>
  <li class="active">Liste des utilisateurs</li>
</ol>
<h2><span class="glyphicon glyphicon-user"></span> Liste des utilisateurs</h2>
<hr/>
<a class="btn btn-primary" href="{{ path('imie_skills_home') }}" role="button"><span class="glyphicon glyphicon-menu-left"></span> Retour</a>
{% if is_granted("ROLE_ADMIN") %}
<a class="btn btn-info" href="{{ path('imie_skills_user_add') }}" role="button"><span class="glyphicon glyphicon-plus"></span> Ajouter un utilisateur</a>
{% endif %}
<hr/>
<table class="table table-striped">
  <thead>
    <th class="col-md-1"></th>
    <th class="col-md-2">Nom</th>
    {#<th class="col-md-3">Promo</th>#}
    <th class="col-md-4">Compétences</th>
    <th class="col-md-1">Modifier</th>
    <th class="col-md-1">Supprimer</th>
  </thead>
  <tbody>
    {% for user in users if users is defined %}
    <tr>
      <td><a href="{{ path('imie_skills_user_details', {id:user.id})}}">{% if user.image %}<img src="{{ asset(user.image.webPath) }}" alt="{{ asset(user.image.imageAlt) }}" width="48" height="48" class="img-circle">{% endif %}</a></td>
      <td><a href="{{ path('imie_skills_user_details', {id:user.id})}}">{{ user.userFullName }}</a></td>
      {#<td>{{ user.promo.course }}</td>#}
      <td>{% if user.skills %}
        <ul>
          {% for tabSkill in user.skills %}
          <li>{{ tabSkill.skill.skillName }}</li>
          {% endfor %}
        </ul>{% endif %}</td>
        {% if ((is_granted("ROLE_ADMIN")) or (user.id == app.user.id)) %}
        <td><a class="btn btn-warning" href="{{ path('imie_skills_user_modify', {id:user.id}) }}" role="button"><span class="glyphicon glyphicon-cog"></span></button></td>
          {% else %}
          <td></td>
          {% endif %}
          {% if is_granted("ROLE_ADMIN") %}
          <td>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target=".user{{user.id}}"><span class="glyphicon glyphicon-trash"></span></button>
            <div class="modal fade user{{user.id}}" tabindex="-1" role="dialog">
              <div class="modal-dialog modal-sm">
                <div class="modal-content">
                  <div class="modal-body">Supprimer l'utilisateur {{ user.userFullName }} ?</div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <a class="btn btn-danger" href="{{ path('imie_skills_user_delete', {id:user.id}) }}" role="button">Confirmer</a>
                  </div>
                </div>
              </div>
            </div>
          </td>
          {% else %}
          <td></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endblock article %}

src/Imie/SkillsBundle/Resources/views/User/modify.html.twig
{% extends 'ImieSkillsBundle::layout.html.twig' %}

{% block article %}
<ol class="breadcrumb">
  <li><a href="{{ path('imie_skills_home') }}">Accueil</a></li>
  <li><a href="{{ path('imie_skills_user_index') }}">Liste des utilisateurs</a></li>
  <li class="active">Modification de l'utilisateur</li>
</ol>
<h2><span class="glyphicon glyphicon-user"></span> Modification de l'utilisateur</h2>
<hr/>
<a class="btn btn-primary" href="{{ path('imie_skills_user_details', {id: app.user.id}) }}"><span class="glyphicon glyphicon-menu-left"></span> Retour</a>
<hr/>
<form method="post" action="{{ path('imie_skills_user_modify', {id: app.user.id}) }}" {{ form_enctype(form) }}>
  {{ form(form) }}
</form>
{% endblock article %}

src/Imie/SkillsBundle/Resources/views/User/update.html.twig
{% extends 'ImieSkillsBundle::layout.html.twig' %}

{% block article %}
<ol class="breadcrumb">
  <li><a href="{{ path('imie_skills_home') }}">Accueil</a></li>
  <li><a href="{{ path('imie_skills_user_details', {id: app.user.id}) }}">Liste des utilisateurs</a></li>
  <li class="active">Modification de l'utilisateur</li>
</ol>
<h2><span class="glyphicon glyphicon-user"></span> Modification de l'utilisateur</h2>
<hr/>
<a class="btn btn-primary" href="{{ path('imie_skills_user_details', {id: app.user.id}) }}"><span class="glyphicon glyphicon-menu-left"></span> Retour</a>
<hr/>
<form method="post" action="{{ path('imie_skills_user_modify', {id: app.user.id}) }}" {{ form_enctype(form) }}>
  {{ form(form) }}
</form>
{% endblock article %}